apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  #local:
  #  push: false #do not push to docker hub
  googleCloudBuild:
    projectId: ticket-dev-337200
  artifacts: #everyhing needs to be built
    - image: us.gcr.io/ticket-dev-337200/auth #orion232/auth for local build
      context: auth #folder contains the image
      docker:
        dockerfile: Dockerfile
      sync: #how to handle all the files changes
        manual:
          - src: "src/**/*.ts"
            dest: . #where to sync the file to
